In [ ]:
# load all .npz files from the raw/ directory
# Each .npz file contains an array of (t_id, 26) list in the "actions" key, and a scalar frequency information in the "num_strikes" key
# Load all .npz files and these keys first
import numpy as np
from pathlib import Path


trajectories = []
frequencies = []
for npz_file in Path("raw").glob("*.npz"):
    data = np.load(npz_file)
    trajectories.append(data["actions"])
    frequencies.append(data["num_strikes"].item())
#     print(data["board_pos"])
# for key in data.keys():
#     print(key)

[0.04523285 0.         0.19346628]
[0.04347686 0.         0.17547505]
[0.04474595 0.         0.19482522]
[0.03751029 0.         0.18334897]
[0.04136499 0.         0.1720658 ]
[0.05597389 0.         0.20094317]
[0.05455117 0.         0.16596231]
[0.04439612 0.         0.18921399]
[0.03328877 0.         0.17505315]
[0.04225282 0.         0.17309925]
[0.05085543 0.         0.18239947]
[0.0545038  0.         0.17106937]
[0.032849   0.         0.18927893]
[0.04742096 0.         0.19948038]
[0.03669011 0.         0.1722591 ]
[0.03379969 0.         0.20026886]
actions
phases
tool_positions
nail_positions
contacts
nail_qpos
strike_hits
strike_first_hit_steps
strike_first_hit_cycle_steps
strike_contact_counts
strike_nail_delta
seed
env_id
controller
pure_action_trajectory
num_strikes
nail_start_qpos
nail_frictionloss
warmup_steps
ramp_steps
retract_steps
settle_steps
goal_distance
action_cycle_max_error
tool_cycle_max_error
relative_cycle_max_error
board_pos
board_pos_default
board_pos_offset
g

In [4]:
print(frequencies)
min_len = 1000
for i in range(len(trajectories)):
    print(trajectories[i].shape)
    min_len = min(min_len, trajectories[i].shape[0])

[3, 4, 4, 3, 5, 5, 6, 6, 4, 6, 3, 3, 4, 6, 5, 5]
(90, 26)
(120, 26)
(120, 26)
(90, 26)
(150, 26)
(150, 26)
(180, 26)
(180, 26)
(120, 26)
(180, 26)
(90, 26)
(90, 26)
(120, 26)
(180, 26)
(150, 26)
(150, 26)


In [5]:
for k in data.keys():
    print(data[k]) if k == "state_driven" else None